events/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^all/', views.all, name='all'),
]

socialauth/urls.py
"""
INTEGRATE EVENTBRITE OAUTH LOGIN IN OUR DJANGO PROJECT
by Cristian Moyano

"""
from django.conf.urls import url, include
from django.contrib import admin
from events.views import home

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^events/', include('events.urls', namespace='events')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
]

events/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

events/views.py
"""
INTEGRATE EVENTBRITE OAUTH LOGIN IN OUR DJANGO PROJECT
by Cristian Moyano

"""
from __future__ import unicode_literals

from django.shortcuts import render
from eventbrite import Eventbrite


def home(request):
    return render(request, 'events/home.html', {})


def all(request):
    access_token = request.user.social_auth.get(
        provider=request.session.get('social_auth_last_login_backend')
    ).access_token
    eventbrite = Eventbrite(access_token)
    events = [
        event
        # Status : live, draft, canceled, started, ended, all
        for event in eventbrite.get(
            '/users/me/events/?status=live,draft'
        )['events']
    ]
    return render(request, 'events/eventos.html', {'events': events})

events/templates/events/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link href="{% static 'events/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'events/css/bootstrap-theme.min.css' %}" rel="stylesheet">
	<link href="{% static 'events/css/main.css' %}" rel="stylesheet">
</head>
<body>
	<div id="body" class="container">
		<div class="col-md-12">
			<div class="navbar navbar-inverse" role="navigation" id="nav">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
					</div>
					<div class="navbar-collapse collapse">
						<ul class="nav navbar-nav">
							<li><a href="{% url 'events:home' %}">Home</a></li>
							{% if user.is_authenticated and not user.is_superuser %}
							<li><a href="{% url 'events:all' %}">events</a></li>
							<li><a href="{% url 'auth:logout' %}?next={% url 'events:home' %}">Logout</a></li>
							{% endif %}
						</ul>
					</div>
					<!--/.nav-collapse -->
				</div>
				<!--/.container-fluid -->
			</div>
		</div>
		<div class="content wrapperContenido col-md-12">
			<div class="contenido bordesContenedores fondoContenedores">
			    {% if messages %}
                    {% for message in messages %}
                        {% if forloop.last %}<p><i>{{ message }}</i></p>{% endif %}
                    {% endfor %}
                {% endif %}
			    <h4>{% block content_title %}{% endblock %}</h4>
			    <hr>
				{% block content %}{% endblock %}
			</div>
		</div>
	</div>
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<!-- Include all compiled plugins (below), or include individual files as needed -->
	<script src="{% static 'thirdauth/js/bootstrap.min.js' %}"></script>
</body>
</html>

events/templates/events/eventos.html
{% extends 'events/base.html' %}

{% block content_title %}Eventos Disponibles{% endblock %}

{% block content %}

{% if events %}
    <ul>
    {% for event in events %}

    <li>Event name:   <b>{{ event.name.html }}   </b> |
        Event start:  <b>{{ event.start.local }} </b> |
        Event end:    <b>{{ event.end.local }}   </b> |
        Event status: <b>{{ event.status }}.     </b>
    </li>

    {% endfor %}
    </ul>

{% else %}
    <p>No tienes ningún evento.</p>
{% endif %}

{% endblock %}

events/templates/events/home.html
{% extends 'events/base.html' %}

{% block content %}

{% if user.is_authenticated and not user.is_superuser %}
    <h3>Bienvenid@ {{ user }}!</h3>
{% else %}
    <a href="{% url 'social:begin' 'eventbrite' %}?next={% url 'events:home' %}" class="btn btn-primary">
        Identificarse con Eventbrite
    </a>

{% endif %}

{% endblock %}